spring:
  application:
    name: db-service
  datasource:
    platform: h2


info:
  component: db service

server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10